baseURL = '//italoamaya.me/'
languageCode = 'en-us'
title = 'Italo Amaya'
# theme = "hugoCoder"
# theme = "cactus"
# theme = "risotto"
theme = "archie"

[markup.goldmark.renderer]
  unsafe = true

disableFastRender = true

[[menu.main]]
  name = "Recipes"
  weight = 4
  url  = "/recipes"

[[menu.main]]
  name = "Home"
  weight = 1
  url = "/"
[[menu.main]]
  name = "About Me"
  weight = 2
  url = "/about"
[[menu.main]]
  name = "Blog"
  weight = 3
  url = "/posts"

# archie
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
[params]
  mode="dark" # color-mode → light,dark,toggle or auto
  mainSections="posts"
	subtitle = "Wellcome to My personal Website. My name is Italo Amaya and if you wish to know more about me then go ahead to my about me page."

# risotto
# [params]
#   [params.about]
#   title = "risotto"
#   description = "A [hugo](https://gohugo.io) theme inspired by terminal ricing."
#   logo = "images/rice.svg"
#   [params.theme]
#   palette = "gruvbox-light"
#   mode = "dark-mode"

# coder
# [params]
  # author = "Italo Amaya"
  # info = "Computer Science Student"
  # # description = "Italo Amaya personal Website"
  # keywords = "blog,developer,personal"
  # math = true
  # since = 2022
  # enableTwemoji = true
  # colorScheme = "dark"

# Cactus
# [params]
  # colortheme = "white" # dark, light, white, or classic
  # description = "lorem ipsum"
  # mainSection = "posts"
  # mainSectionTitle = "Blog"
  # showAllPostsOnHomePage = false
  # postsOnHomePage = 2
  # tocInline = true
  # showProjectsList = false
  # projectsUrl = "https://github.com/italoaa"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/athul/archie"
